apiVersion: v1
appVersion: "348"
description: Deprecated, please use new Trino chart
name: presto
version: 1.2.9
home: https://prestosql.io
sources:
  - https://github.com/valeriano-manassero/helm-charts
  - https://github.com/prestosql/presto
maintainers:
  - name: valeriano-manassero
    email: valeriano.manassero@gmail.com
keywords:
  - presto
  - prestosql
  - prestodb
  - "big data"
  - database
  - sql
  - "query engine"
  - "high performance"
