{{- if .Values.config.worker.autoscaler.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "trino.worker" . }}
spec:
  maxReplicas: {{ .Values.config.worker.autoscaler.maxReplicas }}
  minReplicas: {{ .Values.config.worker.workers }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "trino.worker" . }}
  targetCPUUtilizationPercentage: {{ .Values.config.worker.autoscaler.targetCPUUtilizationPercentage }}
{{- end }}
