apiVersion: v1
kind: Secret
metadata:
  name: trino-connectors
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.connectors }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
