{{- if not .Values.connectorsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trino.fullname" . }}-connectors
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.connectors }}
  {{ $key }}: |-
{{- tpl $val $ | b64enc | nindent 4 -}}
{{- end }}
{{- end }}
---
{{- if and .Values.config.general.authenticationType (not .Values.passwordAuthenticatorProperties) }}{{- if eq .Values.config.general.authenticationType "PASSWORD" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "trino.fullname" . }}-password-authentication
  labels:
    {{- include "trino.labels" . | nindent 4 }}
data:
  password.db: {{ .Values.auth.passwordAuth | b64enc }}
{{- end }}{{- end }}
