{{- if (include "trino.createTlsSecret" . ) }}

{{- $tlsCertStr := regexSplit "###" (include "trino.getTlsCertStrFromSecret" .) -1 }}
{{- $crt := index $tlsCertStr 0 }}
{{- $key := index $tlsCertStr 1 }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-crt" (include "trino.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "trino.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $crt | b64enc | quote }}
  tls.key: {{ $key | b64enc | quote }}
{{- end }}
