apiVersion: v1
appVersion: "343"
description: Distributed SQL query engine for running interactive analytic queries
name: prestosql
version: 1.0.0
home: https://prestosql.io
icon: https://prestosql.io/assets/presto.png
sources:
  - https://github.com/prestosql/presto
maintainers:
  - name: valeriano-manassero
    email: valeriano.manassero@gmail.com
