{{- range .Values.agentGroups }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clearml.fullname" $ }}-agent
  labels:
    {{- include "clearml.labels" $ | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "clearml.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clearml.selectorLabels" $ | nindent 8 }}
    spec:
      volumes:
        {{ if .clearmlConfig }}
        - name: agent-clearml-conf-volume
          secret:
            secretName: {{ .name }}-conf
            items:
            - key: clearml.conf
              path: clearml.conf
        {{ end }}
        - name: agent-data
          persistentVolumeClaim:
            claimName: {{ include "clearml.fullname" $ }}-{{ .name }}-agent-data
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          securityContext:
            privileged: true
          resources:
            limits:
              nvidia.com/gpu:
                {{ .nvidiaGpusPerAgent }}
          env:
          - name: CLEARML_API_HOST
            value: {{ .clearmlApiHost}}
          - name: CLEARML_WEB_HOST
            value: {{ .clearmlWebHost}}
          - name: CLEARML_FILES_HOST
            value: {{ .clearmlFilesHost}}
          - name: CLEARML_AGENT_GIT_USER
            value: {{ .clearmlGitUser}}
          - name: CLEARML_AGENT_GIT_PASS
            value: {{ .clearmlGitPassword}}
          - name: CLEARML_API_ACCESS_KEY
            value: {{ .clearmlAccessKey}}
          - name: CLEARML_API_SECRET_KEY
            value: {{ .clearmlSecretKey}}
          - name: AWS_ACCESS_KEY_ID
            value: {{ .awsAccessKeyId}}
          - name: AWS_SECRET_ACCESS_KEY
            value: {{ .awsSecretAccessKey}}
          - name: AWS_DEFAULT_REGION
            value: {{ .awsDefaultRegion}}
          - name: AZURE_STORAGE_ACCOUNT
            value: {{ .azureStorageAccount}}
          - name: AZURE_STORAGE_KEY
            value: {{ .azureStorageKey}}
          command:
            - /bin/sh
            - -c
            - "apt-get update ;
               apt-get install -y curl python3-pip git;
               python3 -m pip install -U pip ;
               python3 -m pip install clearml-agent{{ .agentVersion}} ;
               CLEARML_AGENT_K8S_HOST_MOUNT=/root/.clearml:/root/.clearml clearml-agent daemon --queue {{ .queues}}"
          volumeMounts:
            - name: agent-data
              mountPath: /root/.clearml
          resources:
            {{- toYaml .resources | nindent 12 }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
