apiVersion: v1
kind: Secret
metadata:
  name: presto-connectors
  labels:
    {{- include "presto.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.connectors }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
