apiVersion: v1
kind: Secret
metadata:
  name: presto-connectors
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $key, $val := .Values.connectors }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
