name: Bug Report
description: Create a report to help us improve
title: "[name of the chart e.g. trino] Issue Title"
labels: [bug]
assignees:
  - valeriano-manassero
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please be cautious with the sensitive information/logs while filing the issue.
  - type: textarea
    id: desc
    attributes:
      label: Describe the bug a clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: helm-version
    attributes:
      label: What's your helm version?
      description: Enter the output of `$ helm version`
      placeholder: Copy paste the entire output of the above 
    validations:
      required: true
  - type: input
    id: kubectl-version
    attributes:
      label: What's your kubectl version?
      description: Enter the output of `$ kubectl version`
    validations:
      required: true
  - type: input
    id: chart-version
    attributes:
      label: What's the chart version?
      description: Enter the version of the chart that you encountered this bug.
    validations:
      required: true
  - type: textarea
    id: changed-values
    attributes:
      label: Enter the changed values of values.yaml?
      description: Please enter only values which differ from the defaults. Enter `NONE` if nothing's changed.
      placeholder: 'key: value'
    validations:
      required: false
