apiVersion: v2
name: clearml
description: MLOps platform
type: application
version: "0.1.5"
appVersion: "1.17"
home: https://allegro.ai
icon: https://raw.githubusercontent.com/allegroai/clearml/master/docs/clearml-logo.svg
sources:
  - https://github.com/valeriano-manassero/helm-charts
  - https://github.com/allegroai/clearml
maintainers:
  - name: valeriano-manassero
    email: valeriano.manassero@gmail.com
keywords:
  - clearml
  - "machine learning"
  - mlops
dependencies:
  - name: redis
    version: "~10.9.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: mongodb
    version: "~10.3.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: elasticsearch
    version: "~7.10.1"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
