apiVersion: v1
appVersion: "433"
description: High performance, distributed SQL query engine for big data
name: trino
version: 9.3.0
kubeVersion: ">= 1.24.0-0 < 1.29.0-0"
home: https://trino.io
icon: https://trino.io/assets/images/trino-logo/trino-ko_tiny-alt.svg
sources:
  - https://github.com/valeriano-manassero/helm-charts
  - https://github.com/trinodb/trino
maintainers:
  - name: valeriano-manassero
    url: https://github.com/valeriano-manassero
keywords:
  - trino
  - trinosql
  - trinodb
  - presto
  - prestosql
  - prestodb
  - "big data"
  - database
  - sql
  - "query engine"
  - "high performance"
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Add ability to adjust logging level of any package.
