apiVersion: v1
appVersion: "419"
description: High performance, distributed SQL query engine for big data
name: trino
version: 6.0.0
kubeVersion: ">= 1.24.0-0 < 1.28.0-0"
home: https://trino.io
icon: https://trino.io/assets/images/trino-logo/trino-ko_tiny-alt.svg
sources:
  - https://github.com/valeriano-manassero/helm-charts
  - https://github.com/trinodb/trino
maintainers:
  - name: valeriano-manassero
    url: https://github.com/valeriano-manassero
keywords:
  - trino
  - trinosql
  - trinodb
  - presto
  - prestosql
  - prestodb
  - "big data"
  - database
  - sql
  - "query engine"
  - "high performance"
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Capabilities to use a custom secret for password authentication
    - kind: added
      description: Capabilities to use a custom secret for fault tolerance
    - kind: changed
      description: How the fault tolerance properties are configured
    - kind: added
      description: Pod labels
    - kind: fixed
      description: Fix container env
    - kind: added
      description: Added container envFrom
    - kind: fixed
      description: Password authentication secret rendering when multiple authentication types are configured
