name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'valeriano-manassero/**'

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run helm-docs
        run: .github/helm-docs.sh
  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.22.7
          - v1.23.6
          - v1.24.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.2.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Add bitnami repo
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - name: Add elstic repo
        run: helm repo add elastic https://helm.elastic.co
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs=valeriano-manassero --target-branch=main)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint and install)
        run: ct lint-and-install --chart-dirs=valeriano-manassero --target-branch=main --helm-extra-args="--timeout=15m" --debug=true
