name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'valeriano-manassero/**'

jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
      - name: Run helm-docs
        run: .github/helm-docs.sh
  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-docs
    strategy:
      matrix:
        k8s:
          - v1.25.8
          - v1.26.3
          - v1.27.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.5.0
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --chart-dirs valeriano-manassero --target-branch main)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
            echo "changed_charts=\"${changed//$'\n'/,}\"" >> "$GITHUB_OUTPUT"
          fi
      - name: Run chart-testing (lint and install)
        run: ct lint-and-install --chart-dirs valeriano-manassero --target-branch main --helm-extra-args "--timeout=15m" --charts=${{steps.list-changed.outputs.changed_charts}} --debug true
        if: steps.list-changed.outputs.changed == 'true'
